---
title: "Epistemology naturalized"
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris
  html_document:
    keep_md: yes
  pdf_document: default
bibliography: "references.bib"
link-citations: yes
---

```{r knitr_opts, cache=FALSE, include=FALSE}
knitr::opts_chunk$set(fig.path = "img/",
                      autodep = TRUE,
                      dpi = 300,
                      fig.asp = 0.5)
```

>However far I go in my distrustful attitude, no actual harm will come of it, because my project won’t
affect how I act, but only how I go about acquiring knowledge. [...] This will be hard work, though, and
a kind of laziness pulls me back into my old ways.

[@descartesMeditationsFirstPhilosophy1614]

In this article, I will outline 
[W. V. O. Quine's](https://en.wikipedia.org/wiki/Willard_Van_Orman_Quine) 
thesis on the development of a naturalistic approach in epistemology 
and the related discussion that has emerged from his proposal. 
I will also present my views on this venture.
The goals of this article are to explore the limits and required conditions 
of science in general and neuroscience in particular,
but also to assess to what extent the scientific study of the mind 
can contribute to the foundation of scientific practice itself. 
I chose to enter into such an endeavour 
through reconstitution of Quine's arguments 
as formulated mainly in the articles 
“*Epistemology Naturalized*” [@quineEpistemologyNaturalized1969]
and “*Two Dogmas of Empiricism*” [@quineTwoDogmasEmpiricism1951], 
and a selective review of articles from the later literature.

## Introduction

Epistemology is the branch of philosophy that deals with human knowledge:
what is knowledge, how we acquire it and what we have the capacity know. 
Its specific objectives are to address the relevant issues
in the context of scientific practice, 
as this can be considered the field in which knowledge processes 
can be better described in relation to common social practice 
but also the field in which epistemological positions have 
the most direct impact.
The roots of epistemology can be traced 
even to the oldest philosophical texts,
and certainly to those of Aristotle and Plato.

### Enlightenment

An important development in this field of human thought
arose with the work of 
[Renè Descartes](https://en.wikipedia.org/wiki/Ren%C3%A9_Descartes)
[@descartesMeditationsFirstPhilosophy1614] 
who tried to base all human knowledge on intuition and deductive logic.
The philosophical current in which such theories of knowledge were articulated
is called *intuitionism* or *foundationalism*, 
which is part of the wider school of thought of 
[*rationalism*](https://en.wikipedia.org/wiki/Rationalism).

Descartes' search for the foundations of knowledge 
emerged from challenging the established beliefs 
and the reliability of sensory experience. 
[David Hume](https://en.wikipedia.org/wiki/David_Hume)
gave a different answer to the same question, 
arguing that any intuition we have 
as well as the ability to reason 
are equally susceptible to error 
as sensory experience,
given that our interface with the world is exclusively through the senses.
The source of unreliability is therefore attributed
to basing our intuitions on our susceptible to error senses.
This is known as the problem of induction 
and one can distinguish its ontological and methodological components.
The ontological component is that 
the concept of causality does not appear to exist in the world; 
even the most stereotypical interaction between objects in the real world 
could evolve differently in some repetition,
without us being able to distinguish the reason for this deviation
-- the methodological component.
Therefore, this thesis leads to a degree of skepticism 
as to what we can know.
Hume argued that our senses are the only way we have to know the world 
and that is enough for our usual needs, 
as long as the world is uniform and does not change suddenly
[@salmonIntroductionPhilosophyScience1999, pp. 66].

Although Hume's position was not initially well received
[@fieserHumeMetaphysicalEpistemological2011; @loseeHistoricalIntroductionPhilosophy2001]
it now holds an important place in the history of philosophy 
and the current that is included is called 
[*empiricism*](https://en.wikipedia.org/wiki/Empiricism).
The next very important contribution to the subject 
was that of [Immanuel Kant](https://en.wikipedia.org/wiki/Immanuel_Kant).
Kant argued that we can have no sensory experience
without the contribution of the mind.
It is in the unchanging and universal 
*a priori* properties of the mind 
that we must focus our attention 
to be able to produce reliable judgments 
and beliefs about the world.
He even suggested a series of *a priori* 
contributions of the mind to the understanding of the world, 
which largely derive their origin from the work of Aristotle
[@mccormickImmanuelKantMetaphysics2020].
He believed that these properties of the mind 
could be deducted using formal logic 
and in combination with the innate spatio-temporal perception 
as well as higher logic, 
can jointly enable the knowledge of the world 
and the construction of a coherent system of knowledge
[@loseeHistoricalIntroductionPhilosophy2001, pp. 96-97].
Kant's view was clearly influenced by Euclidean geometry 
and Newton's mechanics 
[@loseeHistoricalIntroductionPhilosophy2001, p. 97] 
and he likened his achievement 
to the contribution of the Copernican revolution
[@mccormickImmanuelKantMetaphysics2020].

### 20<sup>*th*</sup> century

Through the efforts of Gotlöb Frege and Bertrand Russell 
to reduce mathematics to formal logic, 
a systematic language emerged 
with which older problems could now be described.
After Einstein's theory of relativity challenged 
the universal validity of Newton's theory, 
the philosophers who participated in the so-called "Vienna Circle"
made an attempt to use this propositional logic
to dispel any metaphysics from philosophy.
This historical turning point is often referred to 
as the "*linguistic turn*" in analytic philosophy.
Any observational proposition would now 
be articulated in terms of formal logic 
and would have to be able to be empirically verified 
to be considered meaningful.
This requirement for any proposition 
to be verifiable in order to make sense 
(and not to be placed in the realm of metaphysics)
is known as the *criterion of verifiability* 
and the theoretical framework in which it was articulated,
the [*verification theory of meaning*](https://en.wikipedia.org/wiki/Verificationism).
It would therefore be possible 
to build the necessary set of propositions 
on which scientific practice could be based.
Kant's contribution to the knowledge of the world 
that Kant proposed would have been replaced 
by the grid of logical relations 
between observational propositions 
and the axioms of formal logic.
The scientific propositions would therefore be divided 
into *analytic* and *synthetic*, 
with the former not requiring empirical verification 
and being logically self-evident, 
and the latter being those 
whose meaning derives from their empirical verification.
One of the representatives of 
[*Logical Positivism*](https://en.wikipedia.org/wiki/Logical_positivism), 
as the philosophical current is called, 
who is considered to have managed 
to get closer to the desired achievement was 
[Rudolf Carnap](https://en.wikipedia.org/wiki/Rudolf_Carnap)
[@salmonIntroductionPhilosophyScience1999, p. 85].
More specifically, 
Carnap attempted to structure an inductive logic system 
to the standards of Frege and Russell's deductive logic, 
which would result in an answer to the induction problem 
on the solid basis of formal logic.
The main problem Carnap faced was that, 
even if he managed to complete the task he had undertaken, 
he would have to be able to prove 
the validity of the verifiability criterion itself
within the system he produced 
and how analytic propositions within this system are supported.
But as 
[Kurt Gödel](https://en.wikipedia.org/wiki/Kurt_G%C3%B6del) 
has shown, 
using Hilbert's arsenal of formal logic and mathematical formalism, 
there is no consistent axiomatic (mathematical) system 
in which its own fundamental axioms can be proved.
Therefore, for Carnap to succeed, 
he would have to explain 
the role of analytic propositions in his system.

### The Carnap-Quine dispute

In his article "Empiricism, Semantics, and Ontology"
[@carnapEmpiricismSemanticsOntology1950]
Carnap tries to support the usefulness of the analytic propositions
by separating the possible questions 
that could be asked in relation to the system 
into internal and external.
Internal questions are those 
that can be formulated in terms of the system 
and answered within it;
they can be either empirical questions 
or questions the answers to which can be directly derived
from the use of logic.
External questions, on the other hand, 
are those that cannot be explored empirically.
Such is for example the question 
"Are there spatio-temporal points?".
If it is articulated outside the system, 
its answer is a matter of convention 
and pragmatic faith in the system 
-- otherwise, formulated within the system, 
its answer is analytic and trivial.

Quine's critique in the much-discussed article 
"Two Dogmas of Empiricism” [@quineTwoDogmasEmpiricism1951] 
on Carnap's project focused on two interconnected points.
First, he argued that the attempt to discriminate
between analytic and synthetic sentences 
is artificial and vague.
Such a distinction can not be supported and is not fruitful, 
and therefore is a metaphysical belief 
-- exactly what the empiricists of the Vienna cycle wanted to avoid.
The existence of analyticity becomes problematic 
as the analyticity of a sentence cannot be verified.
Therefore, the criterion of verifiability, 
which is the cornerstone of Logical Positivism, 
cannot be applied.
Quine considers that the doctrine of analyticity, as he calls it, 
is directly related to the second doctrine of Logical Positivism, 
that of reductionism.
He even claims that the two doctrines are identical 
and that we are necessarily led from one to the other 
if we use the criterion of verifiability.
He draws these conclusions by examining 
the different avenues that Carnap tried to follow 
to support the concept of analyticity: 
synonymy, direct definition, and explicit semantic rules, 
and finds them all equally ineffective and vague.
In his view, as long as one is committed to empiricism
one can only accept the confirmatory empirical observations 
as the final evidence for a proposition's degree of truth.

Quine goes even further 
and presents a positive counter-proposition: 
he argues that "the unit of empirical significance is the whole of science" 
[@quineTwoDogmasEmpiricism1951, p. 39].
"The totality of our so-called knowledge or beliefs, 
from the most casual matters of geography and history 
to the profoundest laws of atomic physics or even pure mathematics and logic,
is a man-made fabric which impinges on experience only along the edges."
[@quineTwoDogmasEmpiricism1951, p. 39]
The above passage presents what Quine proposed 
as a replacement for the two doctrines of logical empiricism 
-- the *doctrine of holism*, which he attributed to Duhem 
[@quineEpistemologyNaturalized1969, p. 267].
According to this, 
the whole body of our empirical knowledge 
is tested with every new observation 
and no part of it is immune to revision 
-- every "recalcitrant" observation, 
such that it is not compatible with existing knowledge, 
affects the whole system due to the interconnections between its parts.
Even logic can be revised, 
if this is necessary to maintain the balance of this whole web.
It is this interdependence of the components of our empirical knowledge 
that leads to the famous *indeterminacy of translation*
[@quineEpistemologyNaturalized1969, p. 267].

In his book "Word and Object"
[@quineWordObject1960, p. 29], 
Quine compares the problem of the indeterminacy of translation 
with the analogous problem faced by the anthropologist 
who approaches a previously unknown tribe 
and tries to decipher and translate the language of the natives
that is completely foreign for the anthropologist.
At the sound of the word "Gavagai!" 
and in case this is followed by the happy coincidence
of the native indicating the presence of a rabbit 
that suddenly jumped out of the bushes, 
it is reasonable for the anthropologist 
to assume that the word corresponds to the word "rabbit!" in his own language.
But based on these data alone, 
there are countless other equally plausible alternatives.
For example, the native could have meant 
"a rabbit jumped out of that bush!" 
or "I told you it was there!", 
or "a spatio-temporal blob of matter!" 
or simply "food!".
With just a single observation 
we are not able to ascertain if any of these translations is correct.
But as observations accumulate 
and as they relate to each other, 
possibly also with knowledge of other related languages, 
as is usually the case, 
the more confident we can be for the veracity of translation.

Therefore, a "recalcitrant" empirical observation 
only tells us that something in the way we interpret the world 
is wrong but does not tell us what.
There is no one-to-one correspondence 
between experience and theory 
and therefore the error can be found 
either in the auxiliary hypotheses 
or in the foundations of the knowledge system.
It is said that theory is *underdetermined* by experience
[@hyltonWillardVanOrman2020].
The only way forward is to make some arbitrary choices 
along the way towards the full translation, 
which will only be verifiable and correctable 
based on the following observations.
It is also reasonable to assume that 
concepts are formed in a similar way 
during the development of infants 
and during the development of science
[@quineEpistemologyNaturalized1969, p. 81].

### Towards a naturalistic epistemology

If Quine is right to claim 
that the above analogy between human development and epistemology holds, 
this has important consequences according to him.
On the one hand, 
the possibility of directly reducing epistemology to logic is ruled out,
as infinite possible reconstructions are in principle possible.
All the advantages that such a reduction would have 
(which in the meantime turned into a reduction to logic 
in conjunction with set theory, 
a drastic ontological move according to him) 
-- the "purity" of logic as reliable and self-evident 
and therefore the explanation of empirical data in clearer terms, 
the standardization of scientific explanations 
and the possible simplification of vocabulary --
can not be established
[@quineEpistemologyNaturalized1969, p. 74-75].
This observation leads Quine to note 
that the work Carnap undertook was supposed to provide a rational reconstruction, for which we would have no way of determining whether it was correct.
As we have seen above, 
Carnap has moved away from such a pursuit 
by saying that the building blocks of the system 
are provided through conventions.

At this point Quine wonders:
"But why all this creative reconstruction, 
all this make-believe? [...] 
Why not settle for psychology? [...]
If we are out simply to understand 
the link between observation and science, 
we are well advised to use any available information, 
including that provided by the very science 
whose link with observation we are seeking to understand."
[@quineEpistemologyNaturalized1969, p. 75-76].
The consequence for the fate of epistemology is, 
according to Quine, the following:
"Epistemology in its new setting, conversely, 
is contained in natural science, as a chapter of psychology."
[@quineEpistemologyNaturalized1969, p. 83].
Quine, of course, immediately realizes the circularity of the project.
However, he considers arguments against circularity pointless
"once we have stopped dreaming of deducing science from observations"
[@quineEpistemologyNaturalized1969, p. 76].
He often likens the project to Neurath's boat
[@quineEpistemologyNaturalized1969, p. 84; @quineWordObject1960, p. 3];
the aim is to reconstruct the boat 
while it is already floating in the middle of the sea.
For Quine, the philosopher and the scientist are together on the same boat.
If our goal is the 
"understanding of science as an institution or process in the world, 
and we do not intend that understanding 
to be any better than the science which is its object"
[@quineEpistemologyNaturalized1969, p. 84],
then it is legitimate for this interaction to exist.

At the same time, however, he clarifies that:
"Such a study could still include, even, 
something like the old rational reconstruction, 
to whatever degree such reconstruction is practicable; 
for imaginative constructions 
can afford hints of actual psychological processes, 
in much the way that mechanical simulations can"
[@quineEpistemologyNaturalized1969, p. 83].
A picture of a reciprocal containment emerges:
"The old epistemology aspired to contain, in a sense, natural science; 
it would construct it somehow from sense data. 
Epistemology in its new setting, conversely, 
is contained in natural science, as a chapter of psychology. 
But the old containment remains valid too, in its way. [...]
There is thus reciprocal containment, 
though containment in different senses:
epistemology in natural science and natural science in epistemology."
[@quineEpistemologyNaturalized1969, p. 83]

Quine identifies two consequences arising from the above:
First, the problem of epistemological priority is solved, 
that is, whether observation --and consequently knowledge-- 
consists of sensory data or their conscious awareness.
Epistemological priority is given 
to what is causally closest to the sensory receptors.
In fact, the problem of epistemological priority 
is eliminated as the concept is replaced by causal proximity
[@quineEpistemologyNaturalized1969, p. 84-85].
Second, the notion of the analyticity of an observation sentences
can be replaced by the degree to which it is accepted by the community
[@quineEpistemologyNaturalized1969, p. 86].
The reference to subjectivity is generally eliminated 
as observational propositions will usually concern natural bodies
[@quineEpistemologyNaturalized1969, p. 87].

If we now want to define in this new context 
what an observational proposition is, 
we can say that it is a proposition 
"on which all speakers of the language give the same verdict when given the
same concurrent stimulation.
To put the point negatively, 
an observation sentence is one 
that is not sensitive to differences in past experience 
within the speech community"
[@quineEpistemologyNaturalized1969, p. 86-87].
Outside the realm of language, 
in that of perception 
there is a rather limited set of perceptual patterns, 
"toward which we tend unconsciously to rectify all perceptions. 
These, if experimentally identified, 
could be taken as epistemological building blocks, 
the working elements of experience. 
They might prove in part to be culturally variable, 
as phonemes are, and in part universal."
[@quineEpistemologyNaturalized1969, p. 90].

### Overview

Quine's work is considered to have marked the end of Logical Positivism.
Through Carnap's latest writings 
and Quine's writings presented above, 
analytic philosophy began moving towards pragmatism.
It can be argued that Quine's purpose 
was to save empiricism from the problems that had begun to emerge.
It is clear from his texts that he wishes 
to maintain the criterion of verifiability,
as we have seen it transformed into the new picture,
and he sees, like the empiricists of the Vienna Circle, 
physics as the model science for the construction of the new epistemology.

The metaphysical question that Quine wants to answer 
is how we know the world.
His position is that this question can be answered 
through scientific research.
He therefore rejects the metaphysical doctrine 
of the existence of some form of *a priori* knowledge.
He is led to this metaphysical position 
having rejected the usefulness 
of a distinction between analytic and synthetic propositions, 
seeing scientific methodology as the only alternative approach.
Therefore, he considers that this is an empirical question, 
which can be answered by the psychology of his time.
It can be summarized as how we reach 
what we call knowledge and even science 
from the activations of our sensory receptors.

As Quine himself acknowledges,
the question arises as to whether 
science is legitimized to undertake the task by its own means.
The debate can be traced, to some extent, 
to the disagreement between Kant and Hume 
over what we should trust most, our senses or our reasoning.
Quine brings back the dilemma proposing two new facts:
first, modern science is clearly in a better position 
than in previous centuries 
to explain the apparently complex psycho-mental phenomena;
second, we have ceased to seek 
the absolute certainty that a foundation of knowledge in logic 
or anything else ever tested would offer us.
We will focus in turn on each of the critical issues that arise:
What does the "naturalization" of epistemology mean 
--what does naturalism mean? 
How does Quine himself mean it 
and what other alternatives could be supported?
What objections arise in the first place for the project? 
What is at stake in this proposed transition?

## Discussion

### Naturalism

Like any term, the term *naturalism* can carry different meanings, 
depending on the user, the purpose of its use 
and the context in which it is used.
In a first sense, it may be used to indicate, as an opposition, 
the aversion to anything "supernatural".
Reality is limited to anything found in nature 
--a not-so-informative proposition
[@papineauNaturalism2020; @stroudCharmNaturalism1996].
Almost anyone would agree with that.
The first naturalists of the twentieth century 
already used the term to state that 
all information is contained in nature 
and so everything in it is accessible to the scientific method
[@papineauNaturalism2020].
Based on these,
we can distinguish two components of the term: 
the ontological, that is, 
what someone allows to be included in the "nature" they have in mind, 
and the methodological, what are the limits of the naturalistic approach.
Although the two problems are obviously related, 
we will mainly approach the latter.

What most philosophers who support 
the adoption of naturalism in epistemology seem to agree with 
is the rejection of every *a priori* knowledge 
and even every *a priori* epistemological principle
[@kitcherNaturalistsReturn1992; @rosenbergFieldGuideRecent1996].
The qualification of the scientific methodology 
and empirical search follows from there.
In addition, since naturalists denounce every solid foundation 
they must look for processes or properties 
that are reliable enough to fill in 
the role of *a priori* categories and principles 
(credibility for Kitcher, evolutionary theory for Rosenberg).

A controversy appears to begin 
about the weight that the scientific explanation effort should carry 
and the relative role of philosophy and science.
We can thus distinguish naturalists 
to those who argue that epistemology should be completely replaced by science 
and those who argue that a part of the question remains 
that empirical research cannot access.
This controversy already existed in Quine's writings.

One can detect both 
a version of a "strong" naturalistic approach to epistemology,
but also a "moderate" or "weak" approach
[@haackTwoFacesQuine1993; @stichNaturalizingEpistemologyQuine1993].
The first equates to *scientism*, 
the view that favors science as the best 
and therefore the only method we should use to discover the world, 
while the second sees science as complementary to philosophy 
and possibly as a source for its renewal.

As Haack [-@haackTwoFacesQuine1993] points out, 
among others, this internal conflict in Quine's writings 
arises in part from the different use 
of the term "science" (or "natural science").
We have already seen that Quine proposes 
that the work of epistemology be placed in the academic field of psychology 
--this is a view of the scientistic naturalism that Quine had in mind.
But how can one think of the times 
when Quine considers philosophy and science 
to be part of the same continuum 
(see parable of Neurath's boat) 
or when he tells us that "science is self-conscious common sense"
[@quineWordObject1960, p. 3]?
At other times Quine includes 
economics, sociology, and history in the natural sciences 
[@hyltonWillardVanOrman2020; @sinclairWillardVanOrman2020], 
while denying, arbitrarily to many, 
the contribution of the study of the sociological 
and historical aspects of the issue to epistemology 
[@quineEpistemologyNaturalized1969, p. 87].

Disagreements also arise over how one places oneself 
in the dilemma of realism versus anti-realism.
In simple terms, this dilemma can be expressed as follows: 
is the image of the world that science offers us
an accurate representation of the world itself 
or is it merely an instrumental conceptual form 
that we can use to access it?
One would expect that the certainty required 
to advance the naturalistic approach to the prevailing epistemological approach
would force any proponent to argue that scientific knowledge is real.
But the indeterminacy of translation 
seems to lead directly to anti-realism.
Since two or more theories may equally well 
reflect the incoming empirical observations, 
which of the possible worlds described by them is real?

All these disagreements around 
the degree to which science should be involved in epistemology
stem from the answers the naturalists attempt to provide
to two perceived deficiencies that naturalism is charged with,
the argument from normativity and the argument from circularity, 
as well as from differing opinions 
on the degree of transformation of epistemology itself 
after entrance of naturalism.
We will now examine whether the existence of *a priori* knowledge 
and the possible sources of reliability 
that can emerge in the context of scientific research 
can be supported if we assume the naturalistic approach.

#### The argument from circularity

The first flaw that can be directly identified 
in the naturalistic approach to epistemology 
is that of circularity.
The use of science in the attempt to explain the phenomenon of knowledge 
and of science itself involves circularity: 
it appears to presuppose what is being attempted to explain.
It is tantamount to question begging 
and this is automatically considered condemnatory of any argument: 
the conclusion of the argument necessarily follows from one of the premises.
To put it another way, 
how can one convince Descartes' Skeptic 
that the world of our senses 
is indeed as we know it and we are not deceived?
To achieve this 
(something that would give rise 
to the foundation of empirical science with complete certainty) 
this would have to be done outside the framework of science, 
which is itself based on experience.

An answer given to this argument by the supporters of the naturalistic approach,
following Hume, is that in no way can we overcome our cognitive limitations.
There is no way we can guarantee the certainty of our experience.
As we have seen, Quine tells us that the problem no longer exists, 
as long as we stop dreaming of the logical reconstruction of science.
The problem can be approached scientifically:
"Subtracting his cues from his world view, 
we get man’s net contribution as the difference".
[@quineWordObject1960, p. 4].
Of course, the findings of science 
will not have the certainty that Descartes was aiming for, 
but science has the ability to constantly self-correct.

In addition, according to Gödel's theorems, 
a coherent formal system will either have unjustified initial assumptions 
or will be cyclical and feedback-based
[@sosaNatureUnmirroredEpistemology1983].
Proponents of the naturalistic approach will tend to prefer the latter.
An approach attempting to base knowledge on logic 
--or any other property or process--
would be equally doomed to circularity, 
as it would have to assume itself 
before trying to explain how it leads to knowledge.

Furthermore, a circular argument whose circle is large enough, 
such as a dictionary containing all the words of a language, 
does provide some information and therefore cannot be considered a fallacy 
[@dowdenFallacies2020].
Something analogous in epistemology could be 
to form an as complete as possible dictionary
for the components of knowledge.
Logical Positivism proposed the language of formal logic 
(later supplemented by set theory);
Quine proposed a change of language in favour of the language of science, 
or, in any case, the language that describes the world as it really is.
And it is to be expected that the language itself 
will continue to evolve along the way.
In fact, it is difficult to see how the whole of human knowledge 
can be judged on the same terms 
that circular arguments are judged to be fallacious.
Therefore, in relation to the issue of circularity, 
the two different approaches seem to be equivalent.
In a rational reconstruction, 
assuming that there can exist one 
to be more successful than those already tested, 
one or some of the cognitive or other qualities of man 
(or even human societies)
will be considered the fundamental building blocks 
on which a theory of knowledge will based.
On the other hand, according to the naturalistic approach, 
the equivalent to those foundations (the axioms of science) 
will be under constant review as new empirical data emerge.
In the first case, the circle will be closed at the base of the hierarchy, 
close to the structural elements which will be considered stable 
and any changes will be made to the elements closest to the periphery, 
while in the second, the structural elements can be constantly revised, 
as often as the need arises based on new findings.

#### The argument from normativity

The proposal of adopting the naturalistic approach to epistemology 
has been accused of ignoring the normative aspect of epistemology.
This aspect deals with the search for methods and values 
that should guide us our decision making and our practice,
and in the context of epistemology concerns 
the distinction between right and wrong theories and propositions.
As Rosenberg puts it: 
"Ethics examines what we ought to do, epistemology what we ought to believe"
[@rosenbergNaturalisticEpistemologyEliminative1999].
Hume was the first to point out that 
empirical research findings cannot be applied indiscriminately. 
If we do not want to fall into the naturalistic fallacy,
we must separate *is* from *ought*.

Kim [-@kimWhatNaturalizedEpistemology2008, pp. 540, 542]
argues that Quine was the first to propose 
the removal of the concept of normativity from epistemology 
and its transformation from a project based on justification 
to an empirical quest now based on a descriptive science.
This transition, Kim points out, 
also marks the expulsion of knowledge from epistemology 
[@kimWhatNaturalizedEpistemology2008, p. 542], 
a conclusion with which Quine himself would have little disagreement, 
who had renounced the concept of "knowledge" for serious use, 
along with that of "necessity", "thought", "belief", "experience", "meaning" 
and other terms that he considered vague, 
along with the philosophical questions that required their use, 
because they had no clear boundaries 
[@hyltonWillardVanOrman2020; @soberQuineElliottSober2000].
Stripped of justification and normativity, 
Quine's undertaking bears no resemblance to epistemology, 
the way a traditional epistemologist understands it 
[@kimWhatNaturalizedEpistemology2008, p. 543].

The question that remains is this: 
if normativity is a necessary component of epistemology 
and any comprehensive candidate theory of human knowledge, 
where can it come from and how can it be justified 
to rigorously establish decisions and practice?
The issue at this point intersects with the problems 
that arise in the philosophy of mind.
How do people (or any other organism, society, or community) make decisions, 
and how do they distinguish right from wrong?
We are bound to discussing these issues 
using the so-called intentional vocabulary, 
i.e. based on concepts such as beliefs, intentions, desires, etc.
Therefore, if we want to establish the normativity of epistemology 
we must find a way to explain these concepts 
and how their meanings participate in the phenomena that interest us.

What is certain is that modern epistemology has moved away 
from trying to explain these phenomena 
in terms of the formal logic like Logical Positivism attempted
[@kitcherNaturalistsReturn1992].
If we choose the scientific approach, 
our theories will certainly be descriptive, 
at least in the early stages 
[@churchlandEpistemologyAgeNeuroscience1987].
But if the intentional component of the mind 
can in principle be described 
by any scientific theory that will take on the task, 
we can assume that we will then be able to approach 
the question of which of the mediating processes are reliable 
and which are the ones that provide correct conclusions.
And in this endeavor we can, possibly, 
find some support from evolutionary theory 
[@churchlandEpistemologyAgeNeuroscience1987; @kitcherNaturalistsReturn1992; @quineEpistemologyNaturalized1969; @rosenbergNaturalisticEpistemologyEliminative1999].

The human mind, insofar as it is a product of the human body, 
should be considered the result of biological evolution.
This does not mean, of course, 
that the resulting picture will provide us with 
the necessary certainty against epistemological skepticism.
However, it is able to place the processes that lead to knowledge 
in an evolutionary framework that will not isolate purely human properties 
from the rest of the phylogenetic scale 
while at the same time integrating them with the biological constraints 
(ecological, physical, genetic, etc.) that characterize the human species.
We should therefore expect some degree of inherent uncertainty 
and error introduced through those processes.
The identification of these weaknesses of the human mind 
is rather what leads those who support the naturalistic approach 
to resist an *a priori* consolidated depiction of human knowledge.

## Critical analysis

### The place of Quine's work in modern epistemology

As we have already mentioned, 
Quine's attempt was to salvage the legacy of Logical Positivism, 
transforming as many aspects of it as he considered problematic.
The two main problems he focused on were the two doctrines of empiricism, 
as he called them, 
the doctrine of analyticity and the doctrine of reductionism.
Instead, he proposes a psychologistical study 
of how members of the language community integrate 
and interact to replace analytic and a priori knowledge in general, 
and the doctrine of holism, which in the context of scientific discourse 
is implemented by the web of belief 
and leads to the indeterminacy of translation.

Quine's contribution is now considered by most philosophers 
to have been instrumental in overthrowing the Logical Positivism approach. 
The foundation of *a priori* knowledge in a linguistic approach 
as originally envisioned by Carnap could not succeed. 
Both Carnap himself in his latest writings and Quine showed this.
However, contrary to Quine's approach, 
not everyone agrees that the rejection of foundation in formal logic 
negates the possibility of producing an *a priori* knowledge explanation 
in another framework.

Some, therefore, disagree with Quine's first doctrine 
and the reduction of meaning 
to the stimulation of our sensory receptors
[@friedmanPhilosophicalNaturalism1997; @soberQuineElliottSober2000]. 
Indeed, this approach has the flaws of the behaviorism that Quine embraced. 
Moreover, Quine's approach on the subject, 
while convincing us that the concept of analyticity is vague
no matter how it is defined, 
does not in itself convince us that there must be 
a single way of approaching the concept [@soberQuineElliottSober2000].

The doctrine of holism seems to be less questionable. 
It is generally accepted from Duhem's time 
that no empirical observation can confirm a theoretical hypothesis 
[@loseeHistoricalIntroductionPhilosophy2001, p. 150], 
as more than one auxiliary hypotheses are often considered 
together with some basic assumptions.
It can be argued, however, that Quine's epistemological holism does not follow.
As the most basic assumptions, 
logic and mathematics are not tested in every experiment 
[@friedmanPhilosophicalNaturalism1997; @soberQuineElliottSober2000].
Even if the *a priori* framework proposed by Kant 
or whatever else we can apprehend does not apply,
there must always be some preconditions for empirical science 
that will fulfill the statutory function that, at one reading, Kant meant
[@friedmanPhilosophicalNaturalism1997].

What is certain is that Quine's work in epistemology 
sparked a great deal of debate about 
whether a naturalist epistemology has any merit. 
We will now turn to the assessment of some of the proposals 
that have been expressed from time to time.

### Is a naturalized epistemology possible?

There are many philosophers who have followed Quine's urge 
to introduce an empirical approach to epistemology, 
even if to some extent they do not accept his analysis. 
As we have seen, the contribution of evolutionary theory to this endeavour 
is considered by many to be promising. 
Note here that, as Kitcher estimates 
[@kitcherNaturalistsReturn1992, p. 91, footnote 97], 
evolutionary thinking can contribute to epistemology in two ways: 
either as a theoretical background that will provide the required credibility 
to the processes involved, 
or it will provide the theoretical model, 
analogous to biological evolution, 
on the basis of which a theory of knowledge can be developed in formal terms.

Rosenberg considers that a naturalized epistemology 
is committed to applying evolutionary thinking 
in the attempt to explain the phenomenon of knowledge 
[@rosenbergNaturalisticEpistemologyEliminative1999]. 
For him, this results in the restructuring of the debate 
and its departure from the search for truth 
---the focus on truth does not necessarily ensure survival. 
On the other hand, framing the issue 
in terms of fitness and reproductive success alone 
is not able to give us a picture 
of all the processes involved in the phenomenon. 
We can imagine conditions of evolutionary stress 
in which mental wealth arose accidentally or indirectly, 
due to its relevance to other qualities that provided evolutionary advantage. 
In particular, the mental substrate 
that supports knowledge could be superficial, 
the result of random drift and other non-selective forces 
that evolutionary theory has identified. 
It is reasonable to think, however, 
that such qualities as, for example, "logic", 
which seem to play an important role in human ecology, 
have been selected for in the long-term evolution of humans.

But evolutionary theory can only provide the general theoretical background 
for articulating a comprehensive theory of knowledge 
in the context of the naturalistic approach to epistemology. 
A very large part of the scientific burden 
should be borne by psychology and related sciences. 
It is through studies at this level 
that the possible processes for which all this mental substrate 
is intended will be identified. 
Once these are recognized,
we will be able to produce a comprehensive theory of human knowledge 
that respects the phylogenetic course, 
the ecology of the species during its evolution, 
its ontogenetic and developmental limitations 
and the extent of the relevant traits' diversity. 
At that point we will have reconstructed 
the mental vocabulary of nature 
and we will now be able to reconstruct the scientific practice itself.

It should be emphasized, however, 
that such an endeavour would have to move on more levels 
than science has hitherto done, 
in a somewhat adventurous way, as Lewontin observes 
[@lewontinTripleHelixGene2001, p. 72].

At one level, for example, Stich 
[-@stichNaturalizingEpistemologyQuine1993] 
notes that significant differences are expected to be found 
between individuals in the way they manage available knowledge 
and available scientific findings to form a scientific theory, 
and this differentiation will vary in relation to with factors 
such as education and other cultural characteristics. 
He therefore suggests that epistemology should be interested 
in studying not how each subject manages knowledge, 
but rather the scientists who are most efficient at it. 
Although Stich's proposal needs further support, 
as it does not specify how we will characterize a method as efficient, 
the observation of the neglect of individual differences 
so far by epistemology is positive. 
In fact, Stich is one of the few philosophers 
who fully embraced Quine's urging 
and seeks active collection of empirical data, 
combined with philosophically sensitive analysis
[for example, see [@nicholsMetaskepticismMeditationsEthnoepistemology2003]].

Another dimension that needs to be studied is the social side of knowledge. 
Issues identified by Kitcher [-@kitcherNaturalistsReturn1992] at this level 
are the dissemination of knowledge within the existing social fabric, 
the distinction between personal and impersonal scientific objectives, 
the management of scientific disagreements, 
and the recognition that knowledge subjects 
may have at the same time scientific and non-scientific objectives. 
He considers these issues to be related to the field of social epistemology. 
Issues such as the role of authority in science 
and communication between proponents of opposing theories posed by Kuhn
[-@kuhnStructureScientificRevolutions1996]
can in this context be accessed by empirical science.

In an even broader context, 
naturalized epistemology could study the aims of science over time. 
As it is expected to find that they do not remain constant but change, 
empirical research may identify the criteria by which they change. 
Whether it will be the realizability, 
which Laudan probably reasonably concludes, 
or some still remains in empirical research to determine [@freedmanNormativeNaturalismEpistemic2006].

It follows from the above 
that a post-epistemological current is beginning to develop 
within modern epistemology 
that is interested in studying all possible aspects 
of the phenomena related to human knowledge. 
At another level, the integration of all these perspectives 
into a single theoretical approach 
will be able to provide us with a comprehensive record 
of the processes involved in shaping all the related levels 
and the interactions between them.

Given that the above theoretical framework 
will have emerged from the empirical study, 
a degree of epistemological relativism is expected to dominate. 
But now we have reached the level where we describe 
all human activity related to the phenomenon of knowledge and science, 
and the freedom of choosing between multiple alternatives 
should only be considered an advantage. 
Who would want to be imposed with the way he will act and perceive the world?
I think that this freedom should be ensured 
no matter the ethical framework in place.

Although a thorough presentation is not the subject of the present work, 
efforts have been made to articulate comprehensive theories 
of a more limited extent. 
As an example, one can study the theory of embodied cognition 
and specifically how it develops 
in Damasio's discussion on the creation of consciousness [@antoniordamasioFeelingWhatHappens2000]. 
It is also interesting to see how 
the conceptual framing of philosophical inquiry 
begins to be applied to scientific thought in the field of neuroscience, 
where there has been much talk recently 
about how biological systems can become able to "know" their environment 
through prediction and control [@fristonFreeenergyPrincipleUnified2010], 
something that philosophers set as the goals of knowledge
[@kitcherNaturalistsReturn1992; @rosenbergNaturalisticEpistemologyEliminative1999].

### In conclusion

As has been made clear so far, 
Quine caused a great deal of controversy in the second half of the 20th century
around the foundations of epistemology. 
His main contribution was to identify the impasses of Logical Positivism. 
We must emphasize that his critique focused 
on the distinction between analytical and synthetic propositions, 
and therefore his analysis cannot be considered 
as a rejection of any conceivable *a priori* epistemology. 
Moreover, Quine gives us no convincing reason to believe that 
"humans, branches, stones, electrons, and molecules are indeed real" 
[@sosaNatureUnmirroredEpistemology1983, p. 68].
In essence, it does not tell us how naturalism is legitimized 
to claim that it is handing over the world to us, 
if it cannot show that its theoretical objects are indeed part of nature. 
Another serious limitation is the arbitrary view of 
who is entitled to engage in naturalistic epistemology: 
why not Kuhn or Piaget and even Chomsky with his universal grammar 
(which clearly resists in principle the idea of rejecting the *a priori*). 
Finally, his idea of the psychological view of meaning and knowledge 
is genuinely behaviouristic 
and therefore carries the weaknesses of the approach.

As we have seen before, one element that may be useful in the future 
is the recognition of the non-scientific aspects of knowledge, 
which the unbridled scientism of Quine 
and some of the proponents of the naturalistic approach ignore. 
Ultimately, what is missing from modern epistemology 
is a general framework within which 
all the knowledge produced by the natural sciences can be integrated.
The leap needed is that it should include 
a unified account of the cognitive and biological contexts of reference 
at the same time as the corresponding social and historical perspectives 
on human goals, 
transcending all levels of complexity of the relevant phenomena. 
We have already stressed how important it is for this project 
to be integrated into a more general evolutionary context 
at both the ontogenetic and phylogenetic levels.

This endeavour appears to encounter the obstacle of juxtaposing 
two whole traditions of explanatory models: 
the so-called causal-mechanistic and the holistic 
[@salmonIntroductionPhilosophyScience1999, pp. 33-34]. 
In most cases empirical science tends to look to the causal model. 
But this view stems, I believe, from a short-sighted view 
around the recording of scientific practice. 
Although this model is indeed the most widespread 
in the methodological practices of the sciences, 
often --especially in times of crisis-- 
scientists resort to more holistic explanations. 
I believe that the present situation, 
with the attack of the natural sciences 
on questions about the nature of the phenomena of the mind, 
is one of them.

We can claim that to an extent the struggle between the two approaches, 
which can often co-exist even in the same person, 
reflect the overall relationship of philosophy and science. 
In principle, philosophy is built on a more holistic approach, 
while science is oriented towards the causal explanation 
of the phenomena that surrounds us. 
To the extent that both are intended to make us more conscious of the world --including ourselves--
their practice should be complementary. 
The stakes that arise from the Carnap-Quine controversy 
and the subsequent debate is 
whether the roles of philosophy and science should be distinguished. 
It seems, first of all, that their roles are distinct, 
as philosophy deals with conceptual analysis 
while science with collecting empirical data. 
But empirical science can not be carried out without philosophical thinking 
and philosophy would be pointless if it was developed 
to literally engage with all possible worlds. 
Newton's motivation to oppose 
Descartes's metaphysically-inspired physical science [@loseeHistoricalIntroductionPhilosophy2001, p. 93] 
and the subsequent influence of Newton's work in Kant's thought, 
as we saw, demonstrate this productive interaction in the clearest way.

If we want to deal with the possibility of the existence of *a priori* knowledge
--and with any other issue, as far as I can see--
we have to start with some sort of conceptualization. 
Even more, we are only able to discuss about any issue in the first place 
using the existing conceptualization. 
The development of centuries of philosophy is able to offer us with it. 
But it is expected --and human-- that every concept is flawed. 
For example, although the existence of innate space perception
that Kant presupposed is confirmed, after centuries, by empirical research
[@moserPlaceCellsGrid2008; @palmerKantianViewSpace2010],
it appears to have decisive properties that could not have been accessible 
in Kant's time
[@willsDevelopmentHippocampalCognitive2010].
More recently, Putnam [-@putnamWhyReasonCan1982]
claims that force fields, brown objects and dispositions 
are three non-reducing things or properties. 
Today we know that for brown objects he was wrong, 
we have some theoretical models 
on how fields can be described with simpler terms 
[@wittenUnravellingStringTheory2005]
and some indications that the same could hold 
for the intentional content of the mind. 
So I would say that we are obliged to use the best conceptualization 
that philosophy and philosophical thought in general can offer us, 
but if we would like to make it clearer and in this way more useful, 
we should submit it to any available test.
The tests of scientific methodology have so far turned out to be 
the best to assess the compatibility of a concept with the real world. 
Our best knowledge will always be on retrospection 
and concepts together with their explanations 
will be both remodeled through their interaction.

After all, does science give us a realistic picture of the world? 
The proponent of the naturalistic approach will ask: 
in relation to which reality? 
The theory of evolution suggests that 
there are almost as many ways of seeing (*sic*) the world 
as there are different species 
and the cognitive sciences suggest that diversity 
even among individuals of the same species exists. 
For our species, 
the development of common sense that has acquired self-consciousness, 
as Quine calls science, 
is that which appears to display 
the greatest potential for accurately describing the world. 
We must use its findings with the required respect 
for its limitations and specifications, 
at the cost of continually reviewing its results 
and all the other virtues that make science possible.

Epistemological relativism, 
which is sure to stem from a scientific-type investigation 
into the foundations of epistemology, 
should not frighten us. 
The diversity of the subjects' characteristics, 
their societies and their history 
should be taken for granted and should not be obscured. 
Only through a serious study close to the lines we have outlined 
can a continuous reconstruction of the useful features 
of the related phenomena be produced that will help us to become more and more
aware of our structural relations with the world 
and the interactions between us. 
The human species stands out in this ability to reflect on its own history, 
both individually and collectively. 
And we must pursue this reflection by every means 
at the disposal of the human mind. 
If all this sounds utopian, 
we can not afford to leave it to chance. 
A well-defined dividing line between philosophy and science is of no use 
--only the synthetic adoption of their guidelines by each individual 
can be useful to us.

<blockquote style="text-align:right">
I want to pause and meditate for a while on this new knowledge of mine,
fixing it more deeply in my memory.
</blockquote>

<blockquote style="text-align:right">
I am afraid that my peaceful sleep may be followed by hard labour when I wake,
and that I shall have to struggle not in the light 
but in the imprisoning darkness of the problems I have raised.
</blockquote>
<p style="text-align:right">
[@descartesMeditationsFirstPhilosophy1614]
<p>


## References
